// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i2nNPeRNQPEP9BPre46c64
// Component: SEZ-EKiSKUiS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ProfileHeader from "../../ProfileHeader"; // plasmic-import: T35z79qnz4CS/component
import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import NewLogin from "../../NewLogin"; // plasmic-import: kAqzy6eR7N60/component
import Button from "../../Button"; // plasmic-import: 1hegvDmx6W9E/component

import { useScreenVariants as useScreenVariantsj8Mi7ZgQDQt } from "../library/PlasmicGlobalVariant__Screen"; // plasmic-import: J8mi7ZG-qDQt/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_css from "../library/plasmic.module.css"; // plasmic-import: p1fHvJbiLdgzRrAS359KQb/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: i2nNPeRNQPEP9BPre46c64/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: SEZ-EKiSKUiS/css

import AirplanePlaneFlightSvgrepoComSvgIcon from "./icons/PlasmicIcon__AirplanePlaneFlightSvgrepoComSvg"; // plasmic-import: Pd4zaT4q7XG6/icon
import CityHallSvgrepoComSvgIcon from "./icons/PlasmicIcon__CityHallSvgrepoComSvg"; // plasmic-import: NkOv02nCk4wU/icon
import DepartureAirportSvgrepoComSvgIcon from "./icons/PlasmicIcon__DepartureAirportSvgrepoComSvg"; // plasmic-import: BkpnIEzRskj9/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 3m3fsfx9bNC_/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: G8aALch74DHO/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  profileHeader?: Flex__<typeof ProfileHeader>;
  body?: Flex__<"div">;
  httpRestApiFetcher?: Flex__<typeof DataFetcher>;
  duration2?: Flex__<"section">;
  days3?: Flex__<"div">;
  hours4?: Flex__<"div">;
  minutes3?: Flex__<"div">;
  newLogin?: Flex__<typeof NewLogin>;
  flights2?: Flex__<"div">;
  flightIcon3?: Flex__<"svg">;
  cities2?: Flex__<"div">;
  cityIcon3?: Flex__<"svg">;
  airports2?: Flex__<"div">;
  airportIcon4?: Flex__<"svg">;
  all?: Flex__<typeof Button>;
  _2022?: Flex__<typeof Button>;
  _2023?: Flex__<typeof Button>;
  _2025?: Flex__<"div">;
  _2024?: Flex__<typeof Button>;
  duration?: Flex__<"section">;
  days2?: Flex__<"div">;
  hours3?: Flex__<"div">;
  minutes2?: Flex__<"div">;
  dreamerr?: Flex__<"section">;
  explorerr?: Flex__<"section">;
  adventurer2?: Flex__<"section">;
  globetrotterr?: Flex__<"section">;
  voyager?: Flex__<"section">;
  flights?: Flex__<"div">;
  flightIcon2?: Flex__<"svg">;
  cities?: Flex__<"div">;
  cityIcon2?: Flex__<"svg">;
  airports?: Flex__<"div">;
  airportIcon3?: Flex__<"svg">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "authToken",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return window.decodeURIComponent(
                ("; " + `${window.document.cookie}`)
                  .split("; auth_token=")
                  .pop()
                  .split(";")
                  .shift()
              );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return ``;
              }
              throw e;
            }
          })()
      },
      {
        path: "language",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return ("; " + `${window.document.cookie}`)
                .split("; user_lang=")
                .pop()
                .split(";")
                .shift()
                ? ("; " + `${window.document.cookie}`)
                    .split("; user_lang=")
                    .pop()
                    .split(";")
                    .shift()
                : "en";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return '""';
              }
              throw e;
            }
          })()
      },
      {
        path: "year",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsj8Mi7ZgQDQt()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <ProfileHeader
            data-plasmic-name={"profileHeader"}
            data-plasmic-override={overrides.profileHeader}
            className={classNames("__wab_instance", sty.profileHeader)}
          />

          <div
            data-plasmic-name={"body"}
            data-plasmic-override={overrides.body}
            className={classNames(projectcss.all, sty.body)}
            dir={(() => {
              try {
                return $state.language === "ar" ? "rtl" : "ltr";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          >
            <DataFetcher
              data-plasmic-name={"httpRestApiFetcher"}
              data-plasmic-override={overrides.httpRestApiFetcher}
              className={classNames("__wab_instance", sty.httpRestApiFetcher)}
              dataName={"fetchedData"}
              errorDisplay={
                <DataCtxReader__>
                  {$ctx => (
                    <section
                      className={classNames(projectcss.all, sty.section__rUsIq)}
                    >
                      <section
                        data-plasmic-name={"duration2"}
                        data-plasmic-override={overrides.duration2}
                        className={classNames(projectcss.all, sty.duration2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vhf2H
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.language === "ar"
                                  ? "مدة الوقت في الطيران"
                                  : "Time Spent Flying";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__exRS
                          )}
                        >
                          <div
                            data-plasmic-name={"days3"}
                            data-plasmic-override={overrides.days3}
                            className={classNames(projectcss.all, sty.days3)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ptacx
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return "-";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2Faql
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $state.language === "ar"
                                      ? "أيام"
                                      : "Days";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"hours4"}
                            data-plasmic-override={overrides.hours4}
                            className={classNames(projectcss.all, sty.hours4)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ad2K
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return "-";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lr5Zp
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $state.language === "ar"
                                      ? "ساعات"
                                      : "Hours";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"minutes3"}
                            data-plasmic-override={overrides.minutes3}
                            className={classNames(projectcss.all, sty.minutes3)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5IDye
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return "-";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fW33G
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $state.language === "ar"
                                      ? "دقائق"
                                      : "Minutes";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                        </div>
                      </section>
                      <NewLogin
                        data-plasmic-name={"newLogin"}
                        data-plasmic-override={overrides.newLogin}
                        className={classNames("__wab_instance", sty.newLogin)}
                      />

                      <div
                        data-plasmic-name={"flights2"}
                        data-plasmic-override={overrides.flights2}
                        className={classNames(projectcss.all, sty.flights2)}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__izbTe
                          )}
                        >
                          <AirplanePlaneFlightSvgrepoComSvgIcon
                            data-plasmic-name={"flightIcon3"}
                            data-plasmic-override={overrides.flightIcon3}
                            className={classNames(
                              projectcss.all,
                              sty.flightIcon3
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gLkTd
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "عدد الرحلات"
                                    : "Flights";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pbrEf
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return "-";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"cities2"}
                        data-plasmic-override={overrides.cities2}
                        className={classNames(projectcss.all, sty.cities2)}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wtTGe
                          )}
                        >
                          <CityHallSvgrepoComSvgIcon
                            data-plasmic-name={"cityIcon3"}
                            data-plasmic-override={overrides.cityIcon3}
                            className={classNames(
                              projectcss.all,
                              sty.cityIcon3
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rngH
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "المدن التي زرتها"
                                    : "Cities Visited";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qNuy
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return "-";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"airports2"}
                        data-plasmic-override={overrides.airports2}
                        className={classNames(projectcss.all, sty.airports2)}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dzy5X
                          )}
                        >
                          <DepartureAirportSvgrepoComSvgIcon
                            data-plasmic-name={"airportIcon4"}
                            data-plasmic-override={overrides.airportIcon4}
                            className={classNames(
                              projectcss.all,
                              sty.airportIcon4
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___022Le
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "المطارات التي زرتها "
                                    : "Airports Visited";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </Stack__>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2Ai4G
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return "-";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </section>
                  )}
                </DataCtxReader__>
              }
              errorName={"fetchError"}
              headers={(() => {
                try {
                  return {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                    Authorization: $state.authToken,
                    language: $state.language
                  };
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return {
                      "Content-Type": "application/json",
                      Accept: "application/json"
                    };
                  }
                  throw e;
                }
              })()}
              loadingDisplay={
                <DataCtxReader__>
                  {$ctx => (
                    <section
                      className={classNames(projectcss.all, sty.section__fQPuI)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__uk1Qu)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "desktopDefault")
                            ? "100%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/profile/images/_66E6Ee5D867195738847F3FdAaf7Fa12261301160E09C18600DfGif.gif",
                          fullWidth: 340,
                          fullHeight: 336,
                          aspectRatio: undefined
                        }}
                      />
                    </section>
                  )}
                </DataCtxReader__>
              }
              method={"GET"}
              noLayout={false}
              previewErrorDisplay={
                hasVariant(globalVariants, "screen", "desktopDefault")
                  ? false
                  : false
              }
              previewSpinner={false}
              url={(() => {
                try {
                  return (
                    "https://api.sindibad.iq/api/v1.0/international-flight/Order/mytrips-stat" +
                    $state.year
                  );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "https://api.sindibad.iq/api/v1.0/international-flight/Order/mytrips-stat";
                  }
                  throw e;
                }
              })()}
            >
              <DataCtxReader__>
                {$ctx => (
                  <section
                    className={classNames(projectcss.all, sty.section__wvP09)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__p29D)}
                    >
                      <Button
                        data-plasmic-name={"all"}
                        data-plasmic-override={overrides.all}
                        className={classNames("__wab_instance", sty.all)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateYear"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["year"]
                                  },
                                  operation: 0,
                                  value: "2024"
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateYear"] != null &&
                            typeof $steps["updateYear"] === "object" &&
                            typeof $steps["updateYear"].then === "function"
                          ) {
                            $steps["updateYear"] = await $steps["updateYear"];
                          }
                        }}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return "All Time";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Button";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </Button>
                      <Button
                        data-plasmic-name={"_2022"}
                        data-plasmic-override={overrides._2022}
                        className={classNames("__wab_instance", sty._2022)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateYear"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["year"]
                                  },
                                  operation: 0,
                                  value: "2022"
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateYear"] != null &&
                            typeof $steps["updateYear"] === "object" &&
                            typeof $steps["updateYear"].then === "function"
                          ) {
                            $steps["updateYear"] = await $steps["updateYear"];
                          }
                        }}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return 2022;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Button";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </Button>
                      <Button
                        data-plasmic-name={"_2023"}
                        data-plasmic-override={overrides._2023}
                        className={classNames("__wab_instance", sty._2023)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateYear"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["year"]
                                  },
                                  operation: 0,
                                  value: "2023"
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateYear"] != null &&
                            typeof $steps["updateYear"] === "object" &&
                            typeof $steps["updateYear"].then === "function"
                          ) {
                            $steps["updateYear"] = await $steps["updateYear"];
                          }
                        }}
                      >
                        <div
                          data-plasmic-name={"_2025"}
                          data-plasmic-override={overrides._2025}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty._2025
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return 2023;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Button";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </Button>
                      <Button
                        data-plasmic-name={"_2024"}
                        data-plasmic-override={overrides._2024}
                        className={classNames("__wab_instance", sty._2024)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateYear"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["year"]
                                  },
                                  operation: 0,
                                  value: "2024"
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateYear"] != null &&
                            typeof $steps["updateYear"] === "object" &&
                            typeof $steps["updateYear"].then === "function"
                          ) {
                            $steps["updateYear"] = await $steps["updateYear"];
                          }
                        }}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return 2024;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Button";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </Button>
                    </Stack__>
                    <section
                      data-plasmic-name={"duration"}
                      data-plasmic-override={overrides.duration}
                      className={classNames(projectcss.all, sty.duration)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yliCg
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $state.language === "ar"
                                ? "مدة الوقت في الطيران"
                                : "Time Spent Flying";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bdQ7L
                        )}
                      >
                        <div
                          data-plasmic-name={"days2"}
                          data-plasmic-override={overrides.days2}
                          className={classNames(projectcss.all, sty.days2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xRzdY
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    const minutes =
                                      $ctx.fetchedData.result.duration;
                                    const days = Math.floor(
                                      minutes / (60 * 24)
                                    );
                                    const remainingMinutesAfterDays =
                                      minutes % (60 * 24);
                                    const hours = Math.floor(
                                      remainingMinutesAfterDays / 60
                                    );
                                    const remainingMinutes = String(
                                      remainingMinutesAfterDays % 60
                                    ).padStart(2, "0");
                                    return `${days}`;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lZxM3
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "أيام"
                                    : "Days";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"hours3"}
                          data-plasmic-override={overrides.hours3}
                          className={classNames(projectcss.all, sty.hours3)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tp43G
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    const minutes =
                                      $ctx.fetchedData.result.duration;
                                    const days = Math.floor(
                                      minutes / (60 * 24)
                                    );
                                    const remainingMinutesAfterDays =
                                      minutes % (60 * 24);
                                    const hours = Math.floor(
                                      remainingMinutesAfterDays / 60
                                    );
                                    const remainingMinutes = String(
                                      remainingMinutesAfterDays % 60
                                    ).padStart(2, "0");
                                    return `${hours}`;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__p43Pg
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "ساعات"
                                    : "Hours";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"minutes2"}
                          data-plasmic-override={overrides.minutes2}
                          className={classNames(projectcss.all, sty.minutes2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7BgT
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    const minutes =
                                      $ctx.fetchedData.result.duration;
                                    const days = Math.floor(
                                      minutes / (60 * 24)
                                    );
                                    const remainingMinutesAfterDays =
                                      minutes % (60 * 24);
                                    const hours = Math.floor(
                                      remainingMinutesAfterDays / 60
                                    );
                                    const remainingMinutes = String(
                                      remainingMinutesAfterDays % 60
                                    ).padStart(2, "0");
                                    return `${remainingMinutes}`;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vFl2N
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "دقائق"
                                    : "Minutes";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </div>
                      </div>
                    </section>
                    {(() => {
                      try {
                        return $ctx.fetchedData.result.flights === 0;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <section
                        data-plasmic-name={"dreamerr"}
                        data-plasmic-override={overrides.dreamerr}
                        className={classNames(projectcss.all, sty.dreamerr)}
                      >
                        {(() => {
                          try {
                            return $ctx.fetchedData.result.flights === 0;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__cKff9)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/profile/images/imresizer1734782686280Jpg2.jpg",
                              fullWidth: 1922,
                              fullHeight: 961,
                              aspectRatio: undefined
                            }}
                          />
                        ) : null}
                        {(() => {
                          try {
                            return $ctx.fetchedData.result.flights === 0;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jNxrW
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "لم تسافر بعد. سيقوم سندباد بتحديث إحصائيات رحلاتك مع كل رحلة تكملها."
                                    : "You haven’t traveled yet. Sindibad will refresh your trip stats with every trip you complete.";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        ) : null}
                      </section>
                    ) : null}
                    {(() => {
                      try {
                        return (() => {
                          const flights = $ctx.fetchedData.result.flights;
                          const cities = $ctx.fetchedData.result.cities;
                          const product = flights * cities;
                          const isProductInRange = product > 0 && product < 15;
                          return isProductInRange;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <section
                        data-plasmic-name={"explorerr"}
                        data-plasmic-override={overrides.explorerr}
                        className={classNames(projectcss.all, sty.explorerr)}
                      >
                        {(() => {
                          try {
                            return (() => {
                              const flights = $ctx.fetchedData.result.flights;
                              const cities = $ctx.fetchedData.result.cities;
                              const product = flights * cities;
                              const isProductInRange =
                                product > 0 && product < 15;
                              return isProductInRange;
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__bspQr)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/profile/images/imresizer1734782643234Jpg2.jpg",
                              fullWidth: 1922,
                              fullHeight: 961,
                              aspectRatio: undefined
                            }}
                          />
                        ) : null}
                        {(() => {
                          try {
                            return (() => {
                              const flights = $ctx.fetchedData.result.flights;
                              const cities = $ctx.fetchedData.result.cities;
                              const product = flights * cities;
                              const isProductInRange =
                                product > 0 && product < 15;
                              return isProductInRange;
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xWDbr
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "أنت تجعل كل خطوة مغامرة جديدة مثيرة—لننطلق!"
                                    : "You make every step an exciting new adventure—let’s go!";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        ) : null}
                      </section>
                    ) : null}
                    {(() => {
                      try {
                        return (() => {
                          const flights = $ctx.fetchedData.result.flights;
                          const cities = $ctx.fetchedData.result.cities;
                          const product = flights * cities;
                          const isProductInRange =
                            product >= 15 && product < 35;
                          return isProductInRange;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <section
                        data-plasmic-name={"adventurer2"}
                        data-plasmic-override={overrides.adventurer2}
                        className={classNames(projectcss.all, sty.adventurer2)}
                      >
                        {(() => {
                          try {
                            return (() => {
                              const flights = $ctx.fetchedData.result.flights;
                              const cities = $ctx.fetchedData.result.cities;
                              const product = flights * cities;
                              const isProductInRange =
                                product >= 15 && product < 35;
                              return isProductInRange;
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__p5Ms)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/profile/images/imresizer1734782550827Jpg2.jpg",
                              fullWidth: 1922,
                              fullHeight: 961,
                              aspectRatio: undefined
                            }}
                          />
                        ) : null}
                        {(() => {
                          try {
                            return (() => {
                              const flights = $ctx.fetchedData.result.flights;
                              const cities = $ctx.fetchedData.result.cities;
                              const product = flights * cities;
                              const isProductInRange =
                                product >= 15 && product < 35;
                              return isProductInRange;
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ruhdt
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "أنت تكتب فصلًا جديدًا مع كل رحلة تقوم بها!"
                                    : "You write a new chapter with every trip you take!";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        ) : null}
                      </section>
                    ) : null}
                    {(() => {
                      try {
                        return (() => {
                          const flights = $ctx.fetchedData.result.flights;
                          const cities = $ctx.fetchedData.result.cities;
                          const product = flights * cities;
                          const isProductInRange =
                            product >= 35 && product < 150;
                          return isProductInRange;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <section
                        data-plasmic-name={"globetrotterr"}
                        data-plasmic-override={overrides.globetrotterr}
                        className={classNames(
                          projectcss.all,
                          sty.globetrotterr
                        )}
                      >
                        {(() => {
                          try {
                            return (() => {
                              const flights = $ctx.fetchedData.result.flights;
                              const cities = $ctx.fetchedData.result.cities;
                              const product = flights * cities;
                              const isProductInRange =
                                product >= 35 && product < 150;
                              return isProductInRange;
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__aw7D9)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/profile/images/imresizer1734970995406Jpg.jpg",
                              fullWidth: 1911,
                              fullHeight: 955,
                              aspectRatio: undefined
                            }}
                          />
                        ) : null}
                        {(() => {
                          try {
                            return (() => {
                              const flights = $ctx.fetchedData.result.flights;
                              const cities = $ctx.fetchedData.result.cities;
                              const product = flights * cities;
                              const isProductInRange =
                                product >= 35 && product < 150;
                              return isProductInRange;
                            })();
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return true;
                            }
                            throw e;
                          }
                        })() ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__p0Qhz
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $state.language === "ar"
                                    ? "أنت مسافر متمرس، تكتب القصص أثناء استكشافك للعالم!"
                                    : "You’re a seasoned traveler, crafting stories as you explore the world!";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        ) : null}
                      </section>
                    ) : null}
                    <section
                      data-plasmic-name={"voyager"}
                      data-plasmic-override={overrides.voyager}
                      className={classNames(projectcss.all, sty.voyager)}
                    >
                      {(() => {
                        try {
                          return (() => {
                            const flights = $ctx.fetchedData.result.flights;
                            const cities = $ctx.fetchedData.result.cities;
                            const product = flights * cities;
                            const isProductInRange = product >= 150;
                            return isProductInRange;
                          })();
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__qwgTd)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/profile/images/img10732Jpg2.jpg",
                            fullWidth: 1911,
                            fullHeight: 955,
                            aspectRatio: undefined
                          }}
                        />
                      ) : null}
                      {(() => {
                        try {
                          return (() => {
                            const flights = $ctx.fetchedData.result.flights;
                            const cities = $ctx.fetchedData.result.cities;
                            const product = flights * cities;
                            const isProductInRange = product >= 150;
                            return isProductInRange;
                          })();
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cdNit
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.language === "ar"
                                  ? "لقد رأيت كل شيء، لكن المغامرة لا تنتهي أبدًا!"
                                  : "You’ve seen it all, but the adventure never ends!";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      ) : null}
                    </section>
                    <div
                      data-plasmic-name={"flights"}
                      data-plasmic-override={overrides.flights}
                      className={classNames(projectcss.all, sty.flights)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uHwl
                        )}
                      >
                        <AirplanePlaneFlightSvgrepoComSvgIcon
                          data-plasmic-name={"flightIcon2"}
                          data-plasmic-override={overrides.flightIcon2}
                          className={classNames(
                            projectcss.all,
                            sty.flightIcon2
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__a2ThP
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.language === "ar"
                                  ? "عدد الرحلات"
                                  : "Flights";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ubsKv
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $ctx.fetchedData.result.flights;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"cities"}
                      data-plasmic-override={overrides.cities}
                      className={classNames(projectcss.all, sty.cities)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___8J5MZ
                        )}
                      >
                        <CityHallSvgrepoComSvgIcon
                          data-plasmic-name={"cityIcon2"}
                          data-plasmic-override={overrides.cityIcon2}
                          className={classNames(projectcss.all, sty.cityIcon2)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iCWiq
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.language === "ar"
                                  ? "المدن التي زرتها"
                                  : "Cities Visited";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wMr8R
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $ctx.fetchedData.result.cities;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"airports"}
                      data-plasmic-override={overrides.airports}
                      className={classNames(projectcss.all, sty.airports)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__w9Vct
                        )}
                      >
                        <DepartureAirportSvgrepoComSvgIcon
                          data-plasmic-name={"airportIcon3"}
                          data-plasmic-override={overrides.airportIcon3}
                          className={classNames(
                            projectcss.all,
                            sty.airportIcon3
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kxRP
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.language === "ar"
                                  ? "المطارات التي زرتها "
                                  : "Airports Visited";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ie2Du
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $ctx.fetchedData.result.airports;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  </section>
                )}
              </DataCtxReader__>
            </DataFetcher>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "profileHeader",
    "body",
    "httpRestApiFetcher",
    "duration2",
    "days3",
    "hours4",
    "minutes3",
    "newLogin",
    "flights2",
    "flightIcon3",
    "cities2",
    "cityIcon3",
    "airports2",
    "airportIcon4",
    "all",
    "_2022",
    "_2023",
    "_2025",
    "_2024",
    "duration",
    "days2",
    "hours3",
    "minutes2",
    "dreamerr",
    "explorerr",
    "adventurer2",
    "globetrotterr",
    "voyager",
    "flights",
    "flightIcon2",
    "cities",
    "cityIcon2",
    "airports",
    "airportIcon3"
  ],
  profileHeader: ["profileHeader"],
  body: [
    "body",
    "httpRestApiFetcher",
    "duration2",
    "days3",
    "hours4",
    "minutes3",
    "newLogin",
    "flights2",
    "flightIcon3",
    "cities2",
    "cityIcon3",
    "airports2",
    "airportIcon4",
    "all",
    "_2022",
    "_2023",
    "_2025",
    "_2024",
    "duration",
    "days2",
    "hours3",
    "minutes2",
    "dreamerr",
    "explorerr",
    "adventurer2",
    "globetrotterr",
    "voyager",
    "flights",
    "flightIcon2",
    "cities",
    "cityIcon2",
    "airports",
    "airportIcon3"
  ],
  httpRestApiFetcher: [
    "httpRestApiFetcher",
    "duration2",
    "days3",
    "hours4",
    "minutes3",
    "newLogin",
    "flights2",
    "flightIcon3",
    "cities2",
    "cityIcon3",
    "airports2",
    "airportIcon4",
    "all",
    "_2022",
    "_2023",
    "_2025",
    "_2024",
    "duration",
    "days2",
    "hours3",
    "minutes2",
    "dreamerr",
    "explorerr",
    "adventurer2",
    "globetrotterr",
    "voyager",
    "flights",
    "flightIcon2",
    "cities",
    "cityIcon2",
    "airports",
    "airportIcon3"
  ],
  duration2: ["duration2", "days3", "hours4", "minutes3"],
  days3: ["days3"],
  hours4: ["hours4"],
  minutes3: ["minutes3"],
  newLogin: ["newLogin"],
  flights2: ["flights2", "flightIcon3"],
  flightIcon3: ["flightIcon3"],
  cities2: ["cities2", "cityIcon3"],
  cityIcon3: ["cityIcon3"],
  airports2: ["airports2", "airportIcon4"],
  airportIcon4: ["airportIcon4"],
  all: ["all"],
  _2022: ["_2022"],
  _2023: ["_2023", "_2025"],
  _2025: ["_2025"],
  _2024: ["_2024"],
  duration: ["duration", "days2", "hours3", "minutes2"],
  days2: ["days2"],
  hours3: ["hours3"],
  minutes2: ["minutes2"],
  dreamerr: ["dreamerr"],
  explorerr: ["explorerr"],
  adventurer2: ["adventurer2"],
  globetrotterr: ["globetrotterr"],
  voyager: ["voyager"],
  flights: ["flights", "flightIcon2"],
  flightIcon2: ["flightIcon2"],
  cities: ["cities", "cityIcon2"],
  cityIcon2: ["cityIcon2"],
  airports: ["airports", "airportIcon3"],
  airportIcon3: ["airportIcon3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  profileHeader: typeof ProfileHeader;
  body: "div";
  httpRestApiFetcher: typeof DataFetcher;
  duration2: "section";
  days3: "div";
  hours4: "div";
  minutes3: "div";
  newLogin: typeof NewLogin;
  flights2: "div";
  flightIcon3: "svg";
  cities2: "div";
  cityIcon3: "svg";
  airports2: "div";
  airportIcon4: "svg";
  all: typeof Button;
  _2022: typeof Button;
  _2023: typeof Button;
  _2025: "div";
  _2024: typeof Button;
  duration: "section";
  days2: "div";
  hours3: "div";
  minutes2: "div";
  dreamerr: "section";
  explorerr: "section";
  adventurer2: "section";
  globetrotterr: "section";
  voyager: "section";
  flights: "div";
  flightIcon2: "svg";
  cities: "div";
  cityIcon2: "svg";
  airports: "div";
  airportIcon3: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    profileHeader: makeNodeComponent("profileHeader"),
    body: makeNodeComponent("body"),
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    duration2: makeNodeComponent("duration2"),
    days3: makeNodeComponent("days3"),
    hours4: makeNodeComponent("hours4"),
    minutes3: makeNodeComponent("minutes3"),
    newLogin: makeNodeComponent("newLogin"),
    flights2: makeNodeComponent("flights2"),
    flightIcon3: makeNodeComponent("flightIcon3"),
    cities2: makeNodeComponent("cities2"),
    cityIcon3: makeNodeComponent("cityIcon3"),
    airports2: makeNodeComponent("airports2"),
    airportIcon4: makeNodeComponent("airportIcon4"),
    all: makeNodeComponent("all"),
    _2022: makeNodeComponent("_2022"),
    _2023: makeNodeComponent("_2023"),
    _2025: makeNodeComponent("_2025"),
    _2024: makeNodeComponent("_2024"),
    duration: makeNodeComponent("duration"),
    days2: makeNodeComponent("days2"),
    hours3: makeNodeComponent("hours3"),
    minutes2: makeNodeComponent("minutes2"),
    dreamerr: makeNodeComponent("dreamerr"),
    explorerr: makeNodeComponent("explorerr"),
    adventurer2: makeNodeComponent("adventurer2"),
    globetrotterr: makeNodeComponent("globetrotterr"),
    voyager: makeNodeComponent("voyager"),
    flights: makeNodeComponent("flights"),
    flightIcon2: makeNodeComponent("flightIcon2"),
    cities: makeNodeComponent("cities"),
    cityIcon2: makeNodeComponent("cityIcon2"),
    airports: makeNodeComponent("airports"),
    airportIcon3: makeNodeComponent("airportIcon3"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Trip-Stats",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
